name : Firebase Deployment


on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deployment
    runs-on : ubuntu-latest

    steps:
      - name : get the source code
        uses: actions/checkout@v2

      - name : install node
        uses: actions/setup-node@v2
        with:
            node-version: '12'

      - name : install node packages
        run: npm ci

      - name: Build
        run: npm run build
        env:
          CI: false 
      - name : Deploy to Firebase
        run:  |
           sudo npm install -g firebase-tools
           firebase use dev --token ${{ secrets.FIREBASE_TOKEN }}
           firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}